-- 将该建表 SQL 语句，添加到 yudao-module-design-impl 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "design_screen" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255),
    "simple_desc" varchar(512),
    "bg_img" varchar(255),
    "bg_color" varchar(32),
    "scale_x" int,
    "scale_y" int,
    "components" longtext,
    "design_img_id" varchar(255),
    "state" tinyint,
    "view_code" varchar(255),
    "count_view" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '数据大屏';

-- 将该删表 SQL 语句，添加到 yudao-module-design-impl 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "design_screen";
